apiVersion: v1
kind: Pod
metadata:
  labels:
    run: resource-consumer
    deployment: resource-consumer-1
    deploymentconfig: resource-consumer
  generateName: fake-consumer-
spec:
  containers:
    - image: "docker.io/ocpqe/resource_consumer:v1"
      imagePullPolicy: IfNotPresent
      name: fake-consumer
      ports:
        - containerPort: 8080
          protocol: TCP
      readinessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 36000
        periodSeconds: 3600
      resources:
        requests:
          cpu: 200m
      securityContext:
        capabilities: {}
        privileged: false
      terminationMessagePath: /dev/termination-log
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccount: ""
  terminationGracePeriodSeconds: 30
