apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: medium-priority
value: 50
globalDefault: false
description: "Medium priority class should be used for XYZ service pods only."
